Using temporary directory /tmp/tmp.XPDkfeATxt
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/TagBamWithReadSequenceExtended SUMMARY=../dropseq/SRR6814858/unaligned_tagged_Cellular.bam_summary.txt BASE_RANGE=1-12 BASE_QUALITY=10 BARCODED_READ=1 DISCARD_READ=false TAG_NAME=XC NUM_BASES_BELOW_QUALITY=1 INPUT=../cleandata/SRR6814858.unmappedQuerynamesort.bam OUTPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_Cell.bam
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/TagBamWithReadSequenceExtended SUMMARY=../dropseq/SRR6814858/unaligned_tagged_Molecular.bam_summary.txt BASE_RANGE=13-20 BASE_QUALITY=10 BARCODED_READ=1 DISCARD_READ=true TAG_NAME=XM NUM_BASES_BELOW_QUALITY=1 INPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_Cell.bam OUTPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_CellMolecular.bam
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/FilterBam TAG_REJECT=XQ INPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_CellMolecular.bam OUTPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_filtered.bam
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/TrimStartingSequence OUTPUT_SUMMARY=../dropseq/SRR6814858/adapter_trimming_report.txt SEQUENCE=AAGCAGTGGTATCAACGCAGAGTGAATGGG MISMATCHES=0 NUM_BASES=5 INPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_filtered.bam OUTPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_trimmed_smart.bam
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/PolyATrimmer OUTPUT=/tmp/tmp.XPDkfeATxt/unaligned_mc_tagged_polyA_filtered.bam OUTPUT_SUMMARY=../dropseq/SRR6814858/polyA_trimming_report.txt MISMATCHES=0 NUM_BASES=6 NEW=true INPUT=/tmp/tmp.XPDkfeATxt/unaligned_tagged_trimmed_smart.bam
java -Xmx500m -jar /lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/3rdParty/picard/picard.jar SamToFastq INPUT=/tmp/tmp.XPDkfeATxt/unaligned_mc_tagged_polyA_filtered.bam FASTQ=/tmp/tmp.XPDkfeATxt/unaligned_mc_tagged_polyA_filtered.fastq
STAR --genomeDir /lustre1/lch3000_pkuhpc/liuyt/genome/Mm10_STAR_Index --outFileNamePrefix /tmp/tmp.XPDkfeATxt/star. --readFilesIn /tmp/tmp.XPDkfeATxt/unaligned_mc_tagged_polyA_filtered.fastq --runThreadN 20
java -Dsamjdk.buffer_size=131072 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx4000m -jar /lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/3rdParty/picard/picard.jar SortSam INPUT=/tmp/tmp.XPDkfeATxt/star.Aligned.out.sam OUTPUT=/tmp/tmp.XPDkfeATxt/aligned.sorted.bam SORT_ORDER=queryname TMP_DIR=/tmp/tmp.XPDkfeATxt
java -Xmx4000m -jar /lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/3rdParty/picard/picard.jar MergeBamAlignment REFERENCE_SEQUENCE=/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq-2.3.0/metadata/mm10/mm10.fasta UNMAPPED_BAM=/tmp/tmp.XPDkfeATxt/unaligned_mc_tagged_polyA_filtered.bam ALIGNED_BAM=/tmp/tmp.XPDkfeATxt/aligned.sorted.bam INCLUDE_SECONDARY_ALIGNMENTS=false PAIRED_RUN=false CLIP_ADAPTERS=false TMP_DIR=/tmp/tmp.XPDkfeATxt OUTPUT=/tmp/tmp.XPDkfeATxt/merged.bam
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/TagReadWithInterval I=/tmp/tmp.XPDkfeATxt/merged.bam O=/tmp/tmp.XPDkfeATxt/gene_tagged.bam TMP_DIR=/tmp/tmp.XPDkfeATxt INTERVALS=/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq-2.3.0/metadata/mm10/mm10.genes.intervals TAG=XG
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/TagReadWithGeneFunction O=/tmp/tmp.XPDkfeATxt/function_tagged.bam ANNOTATIONS_FILE=/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq-2.3.0/metadata/mm10/mm10.refFlat INPUT=/tmp/tmp.XPDkfeATxt/gene_tagged.bam
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/DetectBeadSubstitutionErrors INPUT=/tmp/tmp.XPDkfeATxt/function_tagged.bam OUTPUT=/tmp/tmp.XPDkfeATxt/substitution_repaired.bam TMP_DIR=/tmp/tmp.XPDkfeATxt MIN_UMIS_PER_CELL=20 OUTPUT_REPORT=../dropseq/SRR6814858/substitution_error_report.txt
/lustre1/lch3000_pkuhpc/liuyt/software/Drop-seq_tools-2.3.0/DetectBeadSynthesisErrors INPUT=/tmp/tmp.XPDkfeATxt/substitution_repaired.bam MIN_UMIS_PER_CELL=20 OUTPUT_STATS=../dropseq/SRR6814858/synthesis_error_stats.txt SUMMARY=../dropseq/SRR6814858/synthesis_error_summary.txt REPORT=../dropseq/SRR6814858/synthesis_error_report.txt CREATE_INDEX=true TMP_DIR=/tmp/tmp.XPDkfeATxt OUTPUT=../dropseq/SRR6814858/final.bam
Completed successfully.
